language: python
python:
  - "3.6"
install:
    - pip install -r requirements.txt
env:
  - DB=sqlite
  
addons:
  
script:
  - coverage run --omit=*/tests/* test_* *sqlalchemy/* *models/db/sqlalchemy_declarative.py *decimal.py *numbers.py 
  - coverage run nosetests --with -coverage
  
  
cache: pip