language: python

python:
- "3.6"
install:
- pip install coveralls
- pip install -r requirements.txt
env:
- DB=sqlite 
addons: 
script:
- nosetests --with-coverage
after_success:
  - coveralls
cache: pip

notifications:
 email: false

