language: python
python:
  - "3.6"
install:
    - pip install -r requirements.txt
env:
  - DB=sqlite
  
addons:
  
script:
  - --omit=*/tests/* test_* *sqlalchemy/* *models/db/sqlalchemy_declarative.py *decimal.py *numbers.py 
  - nosetests --with -coverage

# after_success:
#  - echo “choose one”

 cache: pip
 
 notifications:
 
 email: false